### ISSUE TITLE
Visualization does not work with too many groups?

### ISSUE THREAD

**Issue by skycrazer** [liamgilbey/ggwaffle#2]
I am trying to do a waffle plot using ggwaffle. I have 8 groups to show. Unfortunately, the output does not show the plot itself, only the legend.

Here is the code I used:

waffle_data <- waffle_iron(mapping, aes_d(group = group_biotype))
ggplot(waffle_data, aes(x, y, fill = group)) + 
  geom_waffle() + 
  coord_equal() + 
  scale_fill_waffle() + 
  theme_waffle()
Here is the output: https://i.stack.imgur.com/90kVn.png

Any idea how to actually see the plot?

Thanks.

**Comment by liamgilbey** [comment]
Hiya,

I'm not convinced it's an issue with the number of groups - you are only trying to plot one more group than the example.

Are you able to share the structure of your `mapping` object you are passing into `waffle_iron`?

**Comment by riddlet** [comment]
I'm encountering a similar bug. I have one dataset that I filtered to create two subsets. The plot works for one of these subsets, but not the other. if I use the waffle_data with geom_tile(), I can get an approximate waffle plot with both, but the geom_waffle seems to just give a blank canvas. Attached are the two datasets generated with waffle_iron. waffle_data1.csv works, waffle_data2.csv does not.

[data.zip](https://github.com/liamgilbey/ggwaffle/files/6051903/data.zip)

**Comment by liamgilbey** [comment]
Right, I understand the issue now. A large number of groups refers to a large number of data points, not a large number of distinct colour groupings.

Using the data you have provided as an example, here is an example that works for both datasets.

```
library((ggwaffle)
library(dplyr)

# download the example data
download.file(
  url = "https://github.com/liamgilbey/ggwaffle/files/6051903/data.zip",
  destfile = "~/temp.zip",
  mode = "wb"
)

# unzip
utils::unzip(
  zipfile = "~/temp.zip",
  exdir = "~/temp"
)

# read in the data
data_1 <- readr::read_csv(
  "~/temp/data/waffle_data1.csv"
)
data_2 <- readr::read_csv(
  "~/temp/data/waffle_data2.csv"
)

# plot #1
p1 <- ggplot(
  data_1, 
  aes(x, y, fill = group)
  ) +
  geom_waffle()

ggsave(
  filename = "/mnt/host/image1.png",
  plot = p1,
  dpi = 500,
  width = 10,
  height = 10
)

# plot #2
p2 <- ggplot(
  data_2, 
  aes(x, y, fill = group)
) +
  geom_waffle()

ggsave(
  filename = "/mnt/host/image2.png",
  plot = p2,
  dpi = 100,
  width = 30,
  height = 30
)
```
The only way this works is by exporting massively oversized images that allow you to actually see all the data.

![image1](https://user-images.githubusercontent.com/8405101/109374076-9a9b2680-7917-11eb-8476-0346864e027f.png)

![image2](https://user-images.githubusercontent.com/8405101/109374080-9f5fda80-7917-11eb-9b7b-266795d5223e.png)



The problem lies in the sheer number of points trying to be displayed, and all that `geom_waffle` is providing is essentially a thin wrapper around `geom_tile` with white borders around each tile. When trying to plot that many points, all we end up seeing at a small scale is the white borders...

It is likely still possible to display all this data at once, you'll just have to play around with text size etc. to get something legible in the end.

**Comment by philippbayer** [comment]
I also just stumbled over this one, here's my workaround to use only every tenth sighting (adjust as necessary), i.e., every box coutns for ten sightings, not just one

```
  df %>% 
  select(species, Group) %>% unique() %>%
  group_by(Group) %>%
  slice(if (n() >= 10) seq(10, n(), by = 10) else n()) %>%  # If >=10 rows, take every 10th; if <10, take all
  ungroup() %>%
  waffle_iron(aes_d(group = Group)) %>%
  ggplot(aes(x, y, fill = group)) +
  geom_waffle() +
  coord_equal() +
  scale_fill_waffle() +
  theme_waffle() 
```
